### ISSUE TITLE
请问可以训练了吗

### ISSUE THREAD

**Issue by ustczhouyu** [chenjun2hao/FOTS.pytorch#2]
请问可以训练了吗，我训练的时候报错了：
Traceback (most recent call last):
  File "train.py", line 111, in main
    ctcl, gt_target , gt_proc = process_boxes(images, im_data, seg_pred[0], roi_pred[0], angle_pred[0], score_maps, gt_idxs, gtso, lbso, features, net, ctc_loss, opts, converter, debug=opts.debug)
  File "/home/zy1992/jupyter/27_years_old/end-to-end/latest_fots/src/ocr_process.py", line 263, in process_boxes
    maxratio = rois[:, 4] / rois[:, 3]
IndexError: too many indices for tensor of dimension 1
epoch 0[25], loss: 195.313, bbox_loss: 10.288, seg_loss: -0.212, ang_loss: 0.198, ctc_loss: 189.771, time 0.404

**Comment by zhangjunyi1225054736** [comment]
我也遇到了这个问题，请问您解决了吗

**Comment by zhangjunyi1225054736** [comment]
求回复～～
